### ISSUE TITLE
Annual leave tracking

### ISSUE THREAD

**Issue by anorthall** [anorthall/northall.me.uk#21]
There should be a method of tracking annual leave.

## Implementation
- [ ] A model for a week of annual leave, and a model for a lieu day
- [ ] The week of annual leave should verify no shifts within the week, and the lieu day should verify no shift on the date
- [ ] Shifts should not allow themselves to be added during annual leave or on a lieu day
- [ ] Annual leave should have a selection for 'booked' or 'taken' (automatically switch)
- [ ] Lieu days should have a selection for 'requested' or 'taken' (do not automatically switch)
- [ ] Annual leave and lieu days should be displayed on timesheets
