### ISSUE TITLE
Pay tracking

### ISSUE THREAD

**Issue by anorthall** [anorthall/northall.me.uk#23]
The tracker should be able to calculate the amount of pay due between any two specific dates.

### Modelling
- [ ] A model for pay data - a model which holds an hourly rate, with a start and end date for that rate, in order to account for differing payscales over the lifetime of the app.
- [ ] The above model should not allow overlaps - only one pay date for any specific date.
- [ ] The model should include the amount payable for overtime at an enhanced rate for the specified period.
- [ ] The most recent pay data should apply indefinitely into the future.
- [ ] The first (oldest) pay data should apply indefinitely into the past.

### Views
- [ ] A view that allows the user to select a start and end date, and all pay due between those two dates is calculated (intended to be used to see the pay due over a pay period (4 weeks)).
- [ ] Each day must be calculated separately, to allow for differing pay rates over the selected period.
- [ ] Overtime should be accounted for at different rates. (A toggle will need adding to `Shift` to designate a shift as overtime)
- [ ] The base salary should be calculated on the basis of a 35 hour week, and then overtime added to produce the total pay due.
