### ISSUE TITLE
Tracker does not have sufficient unit tests

### ISSUE THREAD

**Issue by anorthall** [anorthall/northall.me.uk#7]
## Current behaviour
Only some unit tests are implemented.

## Expected behaviour
Unit tests for all methods and models.

## Implementation
The following unit tests require implementation (possibly more):

- [ ] `Shift.miles()` - including when no Diagram is selected
- [ ] `Shift.minutes()` - including when no Diagram is selected
- [ ] `Diagram.clean()` 
- [ ] `Shift.clean()`
- [ ] `Shift.diagram_str()`
- [ ] `Unit.times_driven()`
- [ ] `Unit.first_driven()`
- [ ] `Unit.last_driven()`
- [ ] `Unit.train_class()`

Additionally:

- [ ] Make a method of generating a test database full of data
